version: "3.4"

services:
  app:
    build:
      context: .
      target: development
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: fundocker/ralph:development
    env_file:
      - .env
    environment:
      PYLINTHOME: /app/.pylint.d
    volumes:
      - .:/app
    networks:
      default:
        
  # -- backends
  elasticsearch:
    image: elasticsearch:7.13.3
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
    networks:
      potsie:
        aliases:
          - elasticsearch
      default:

  swift:
    image: kklopfenstein/openstack-swift-keystone-docker
    ports:
      - "49177:8080"
      - "49178:35357"
    environment:
      KS_SWIFT_PUBLIC_URL: http://127.0.0.1:49177

  mongo:
    image: mongo:4.2
    networks:
      default:

  graylog:
    image: graylog/graylog:4.2.1
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      default:
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 9000:9000
      - 12201:12201

  # -- tools
  dockerize:
    image: jwilder/dockerize

networks:
  potsie:
    name: potsie
    external: true
